//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingAppEF2.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int ID { get; set; }
        public string Acronym { get; set; }
        public Nullable<double> Value { get; set; }
        public string Category { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
